[package]
name = "net3_codec_msgpack"
version = "0.1.0"
authors = ["Łukasz Kurowski <crackcomm@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "^1.1"

serde = "^1.0"
rmp-serde = "^0.14.3"

tokio = "^1"
tokio-util = { version = "^0.6.9", features = ["codec"] }

